# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

from fsq_agent.application._errors import normalize_application_error
from fsq_agent.application.cases import create_case, test_case
from fsq_agent.application.contracts import (
    ApplicationError,
    ApplicationErrorCategory,
    ApplicationErrorCode,
    ApplicationRecordType,
    CaseCreateEventSink,
    CaseCreateRequest,
    CaseCreateResult,
    CaseTestRequest,
    CaseTestResult,
    DoctorChecks,
    DoctorCommands,
    DoctorPlatformResult,
    DoctorRequest,
    DoctorResult,
    DoctorStatusDetail,
    DoctorWorkspaceSummary,
    EnvironmentSummary,
    GenerateRunHtmlRequest,
    GenerateRunHtmlResult,
    ListRunsRequest,
    ListRunsResult,
    ProviderConfigurationResult,
    ProviderStatusResult,
    ReadRunLogsRequest,
    ReadRunLogsResult,
    RunArtifactIndex,
    RunDetail,
    RunLogEvent,
    RunMetadata,
    RunResultSummary,
    RunRuntime,
    RunSource,
    RunStepCounts,
    RunSummary,
    ShowRunRequest,
    ShowRunResult,
    WorkspaceInitializeRequest,
    WorkspaceInitializeResult,
    WorkspaceRequest,
    WorkspaceResult,
    event_record,
    result_record,
)
from fsq_agent.application.doctor import diagnose_workspace
from fsq_agent.application.environments import list_environments
from fsq_agent.application.providers import complete_github_configuration, configure_azure_openai, provider_status, request_github_device_code
from fsq_agent.application.runs import generate_run_html, list_runs, read_run_logs, show_run
from fsq_agent.application.workspace import add_workspace_platform, create_workspace, initialize_workspace, require_initialized_workspace, resolve_workspace_target, update_workspace_platform

__all__ = [
    "ApplicationError",
    "ApplicationErrorCategory",
    "ApplicationErrorCode",
    "ApplicationRecordType",
    "CaseCreateEventSink",
    "CaseCreateRequest",
    "CaseCreateResult",
    "CaseTestRequest",
    "CaseTestResult",
    "DoctorChecks",
    "DoctorCommands",
    "DoctorPlatformResult",
    "DoctorRequest",
    "DoctorResult",
    "DoctorStatusDetail",
    "DoctorWorkspaceSummary",
    "EnvironmentSummary",
    "GenerateRunHtmlRequest",
    "GenerateRunHtmlResult",
    "ListRunsRequest",
    "ListRunsResult",
    "ProviderConfigurationResult",
    "ProviderStatusResult",
    "ReadRunLogsRequest",
    "ReadRunLogsResult",
    "RunArtifactIndex",
    "RunDetail",
    "RunLogEvent",
    "RunMetadata",
    "RunResultSummary",
    "RunRuntime",
    "RunSource",
    "RunStepCounts",
    "RunSummary",
    "ShowRunRequest",
    "ShowRunResult",
    "WorkspaceInitializeRequest",
    "WorkspaceInitializeResult",
    "WorkspaceRequest",
    "WorkspaceResult",
    "add_workspace_platform",
    "complete_github_configuration",
    "configure_azure_openai",
    "create_case",
    "create_workspace",
    "diagnose_workspace",
    "event_record",
    "generate_run_html",
    "initialize_workspace",
    "list_environments",
    "list_runs",
    "normalize_application_error",
    "provider_status",
    "read_run_logs",
    "request_github_device_code",
    "require_initialized_workspace",
    "resolve_workspace_target",
    "result_record",
    "show_run",
    "test_case",
    "update_workspace_platform",
]
